version: '3'

services:
  psd:
    container_name: psd
    image: postgres:14.1
    ports:
      - "127.0.0.1:5470:5432"
    env_file:
      - .env
    environment:
      - .env
    networks:
    - app-network
    volumes:
      - dir:/app/static
    restart: always
networks:
  app-network:
    driver: bridge
volumes:
  dir: